### ISSUE TITLE
Hardware source requirement.

### ISSUE THREAD

**Issue by ENJOY-Yin-jiong** [cientgu/VQ-Diffusion#1]
Nice work, and thanks to your kindful share! But I wonder the GPU requirement for the training and how to switch the VQ-Diffusion-S for the training? Looking forward to your reply!

**Comment by cientgu** [comment]
> Nice work, and thanks to your kindful share! But I wonder the GPU requirement for the training and how to switch the VQ-Diffusion-S for the training? Looking forward to your reply!

For all the experiments in the paper except pretraining on CC dataset, we use only 8 V100s. For training VQ-Diffusion-S, we provided the details in the appendix, and also, we provide a training config on cub200 dataset (configs/cub200_s.yaml). Hope it can help you.

**Comment by ENJOY-Yin-jiong** [comment]
Thanks for timely reply, it really useful to me.
