### ISSUE TITLE
Results of running pretrained models

### ISSUE THREAD

**Issue by ShovalMessica** [cientgu/VQ-Diffusion#2]
Hi,
I run pretraind_human, pretrained_imagenet and get not so good results.
Is additional training required?
Thank you!

**Comment by cientgu** [comment]
> Hi, I run pretraind_human, pretrained_imagenet and get not so good results. Is additional training required? Thank you!

Due to the computation cost, the training epoch and model size may not enough. So the results may not be perfect. More training will improve the performance. However, without additional training, these results make sense.

**Comment by abhigoku10** [comment]
@ShovalMessica  where u able to download the pre trained weights if so can u share in google drive or one drive
