### ISSUE TITLE
Error for loading state_dict for DALLE

### ISSUE THREAD

**Issue by jcy132** [cientgu/VQ-Diffusion#27]
Got runtime error for training command for CUB data
(" python running_command/run_train_cub.py " )

RuntimeError: Error(s) in loading state_dict for DALLE:
	Unexpected key(s) in state_dict: "transformer.log_alpha", "transformer.log_1_min_alpha", "transformer.log_cumprod_alpha", "transformer.log_1_min_cumprod_alpha".

Any point that I missed?

**Comment by zhangyuxuan537** [comment]
How did you resolve this error?
