### ISSUE TITLE
Cub200Dataset

### ISSUE THREAD

**Issue by yangdongchao** [cientgu/VQ-Diffusion#4]
Hi , thanks for your code.
I want to run your code on CUB200 dataset. I download this dataset from http://www.vision.caltech.edu/visipedia/CUB-200.html. But I find that it does not incude filenames.pickle files. Furthermore the annotation of this dataset is .mat format, but in your  dataset code, the anotation seems .txt format. (this_text_path = os.path.join(data_root, 'text', 'text', name+'.txt')).
So I want to ask whether you can tell me how to get the CUB200 dataset as your description.

Looking forward to your reply.

**Comment by cientgu** [comment]
You may download these corresponding files here (https://drive.google.com/file/d/1L6Nf6AcxUrdVr1KTlcUlq38isGypo5DP/view?usp=sharing).

**Comment by yangdongchao** [comment]
> You may download these corresponding files here (https://drive.google.com/file/d/1L6Nf6AcxUrdVr1KTlcUlq38isGypo5DP/view?usp=sharing).

Thank you very much
