### ISSUE TITLE
How to set using Mutiple GPUs to train?

### ISSUE THREAD

**Issue by yangdongchao** [cientgu/VQ-Diffusion#5]
Hi, can you share how to use multiple GPUs to train the code?
According to you scripts in running_command folder, it seems only support use one single GPU.

**Comment by cientgu** [comment]
--num_node does not mean single GPU, but GPUs on a single node, this code supports multiple GPUs on a single node and multiple nodes training.

**Comment by yangdongchao** [comment]
> --num_node does not mean single GPU, but GPUs on a single node, this code supports multiple GPUs on a single node and multiple nodes training.

Thanks you, I have solve this problems.
