### ISSUE TITLE
question about 'filter_ratio' parameter

### ISSUE THREAD

**Issue by yzxing87** [cientgu/VQ-Diffusion#7]
Hi, thanks for the excellent implementation!

Could you please tell me what is the purpose of the 'filter_ratio' parameter in [the sampling function](https://github.com/cientgu/VQ-Diffusion/blob/56cc8134eff25385beb4e0fd83896857ddf392b4/image_synthesis/modeling/transformers/diffusion_transformer.py#L463)? And I also note that the intermediate training results are sampled with different filter_ratio parameters. How should we interpret the results with different values? Thanks!

**Comment by cientgu** [comment]
This is just for debugging in the training procedure. To make sure each denoising step works well.

**Comment by yzxing87** [comment]
Thanks for the clarification.
